from typing import Protocol


class LlmClient(Protocol):
    """Interface for interaction with Large Language Models.

    Facilitates text generation based on structured or unstructured prompts.
    """

    def generate(self, prompt: str) -> str:
        """Generates a response based on the provided prompt.

        Args:
            prompt: User input or instructions for the model.

        Returns:
            The text response generated by the model.

        Raises:
            LlmError: If an error occurs during the generation process.
        """
        ...
