from typing import Protocol


class LlmClient(Protocol):
    def generate(self, prompt: str) -> str:
        """Generates a response based on the provided prompt.

        Args:
            prompt: User input or instructions for the model.

        Returns:
            The text response generated by the model.

        Raises:
            LlmError: If any error occurs during the generation process.
        """
        ...
