"""add_source_to_quotes

Revision ID: 203b34a62cd6
Revises: 4cad4e3d31c8
Create Date: 2026-04-29 12:45:44.629987

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "203b34a62cd6"
down_revision: Union[str, Sequence[str], None] = "4cad4e3d31c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("quotes", sa.Column("source", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quotes", "source")
    # ### end Alembic commands ###
